config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :vendors
  resources :books do
    resources :requests
  end
  root "books#index"
  get "/search", to:"books#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user, :optional => true
	has_many :requests

	def self.search_by(search_term)
		where("LOWER(bookname) LIKE :search_term OR LOWER(bookdescription) LIKE :search_term OR LOWER(author) LIKE :search_term OR LOWER(vendorname) LIKE :search_term OR LOWER(vendormail) LIKE :search_term OR LOWER(status) LIKE :search_term OR LOWER(vendorname) LIKE :search_term OR LOWER(vendormail) LIKE :search_term OR LOWER(position) LIKE :search_term ",search_term: "%#{search_term.downcase}%")
	end
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vendor.rb
class Vendor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
    if params[:search]
      @search_term = params[:search]
      @books = @books.search_by(@search_term)
    end
  end


  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:bookname, :bookdescription, :vendorname, :vendormail, :userid, :status, :position, :author)
    end



end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[ show edit update destroy ]

  # GET /requests or /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1 or /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests or /requests.json
  def create
    @book = Book.find(params[:book_id])
    @request = @book.requests.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @book, notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: "Request was successfully updated." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: "Request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.require(:request).permit(:request, :book_id, :parent_id, :user_id)
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: %i[ show edit update destroy ]

  # GET /vendors or /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1 or /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors or /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: "Vendor was successfully created." }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1 or /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: "Vendor was successfully updated." }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1 or /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: "Vendor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vendor_params
      params.require(:vendor).permit(:vendor_name, :vendor_mail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/books/_form.html.erb
<style type="text/css">
  .form-control1{
    background: none;
    border: none;
    border-bottom: solid white thin;
    color: white;
    padding: 5px;
    margin: 5px;
    width: 400px;
  }
  
</style>


<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <form>
  <div class="form-group" style=" margin: 0 auto;margin-top:10%;">
  <div class="field">
    <%= form.label :bookname %><br>
    <%= form.text_field :bookname,class:"form-control1" %>
  </div>

  <div class="field form-group">
    <%= form.label :bookdescription %><br>
    <%= form.text_field :bookdescription,class:"form-control1" %>
  </div>

  <div class="field form-group">
    <%= form.label :author %><br>
    <%= form.text_field :author,class:"form-control1" %>
  </div>

  <div class="field">
    <%= form.label :vendorname %><br>
    <%= form.text_field :vendorname,class:"form-control1" %>
  </div>

  <div class="field">
    <%= form.label :vendormail %><br>
    <%= form.text_field :vendormail,class:"form-control1" %>
  </div>

  <div class="field">
    <%= form.text_field :userid, value:current_user.id, type: :hidden %>
  </div>

  <div class="field">
    <%= form.label :status %><br>
    <%= form.text_field :status,class:"form-control1" %>
  </div>

  <div class="field">
    <%= form.label :position %><br>
    <%= form.text_field :position,class:"form-control1" %>
  </div><br>

  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>
</div>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</form>

app/views/books/edit.html.erb
<style>
  .tbl-content{
  height:800px;
  overflow-x:auto;
  margin-top: 0px;
  border: 1px solid rgba(255,255,255,0.3);
  margin-right: 20%;
  margin-left: 20%;
  padding: 20px;
  color: white;
}
</style>
	<br><br>
<br><br>
<div class="tbl-content">
<h1>Editing Book</h1>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<%= render 'form', book: @book %>
<div class="col-md-4 col-md-offset-4"><br>
<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>
</div>
</div>

app/views/books/index.html.erb
<style type="text/css">
 h1{
  font-size: 30px;
  color: #fff;
  text-transform: uppercase;
  font-weight: 300;
  text-align: center;
  margin-bottom: 15px;
}
table{
  width:100%;
  table-layout: fixed;
}
.tbl-header{
  background-color: rgba(255,255,255,0.3);
 }
.tbl-content{
  height:300px;
  overflow-x:auto;
  margin-top: 0px;
  border: 1px solid rgba(255,255,255,0.3);
}
th{
  padding: 20px 15px;
  text-align: left;
  font-weight: 500;
  font-size: 12px;
  color: #fff;
  text-transform: uppercase;
}
td{
  padding: 15px;
  text-align: left;
  vertical-align:middle;
  font-weight: 300;
  font-size: 12px;
  color: #fff;
  border-bottom: solid 1px rgba(255,255,255,0.1);
}

tr:hover{
  background-color: rgba(255,255,255,0.3);
}
/* demo styles */

@import url(https://fonts.googleapis.com/css?family=Roboto:400,500,300,700);
body{
  background: -webkit-linear-gradient(left, #25c481, #25b7c4);
  background: linear-gradient(to right, #25c481, #25b7c4);
  font-family: 'Roboto', sans-serif;
}
section{
  margin: 50px;
}


/* follow me template */
.made-with-love {
  margin-top: 40px;
  padding: 10px;
  clear: left;
  text-align: center;
  font-size: 10px;
  font-family: arial;
  color: #fff;
}
.made-with-love i {
  font-style: normal;
  color: #F50057;
  font-size: 14px;
  position: relative;
  top: 2px;
}
.made-with-love a {
  color: #fff;
  text-decoration: none;
}
.made-with-love a:hover {
  text-decoration: underline;
}


/* for custom scrollbar for webkit browser*/

::-webkit-scrollbar {
    width: 6px;
} 
::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
} 
::-webkit-scrollbar-thumb {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
}
</style>
<% if user_signed_in? %>
<br><br><br><br><br>
<p id="notice"><%= notice %></p>
<section>
  <h1>BOOKS TABLE</h1>
  <div class="tbl-header">
    <table cellpadding="0" cellspacing="0" border="0">
      <thead>
        <tr>
          <th>Bookname</th>
          <th>Bookdescription</th>
          <th>Author</th>
          <th>Bookposition</th>
          <th>Bookstatus</th>

          <%  if current_user.email=="admin@gmail.com" %>

          <th>Vendorname</th>
          <th>Vendormail</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <% else %>
          <th></th>
          <th></th>
        <% end %>

        </tr>
      </thead>
    </table>
  </div>
  <div class="tbl-content">
    <table cellpadding="0" cellspacing="0" border="0">
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= book.bookname %></td>
            <td><%= book.bookdescription %> </td>
            <td><%= book.author %></td>
            <td><%= book.position %></td>
            <td><%= book.status %></td>
            <%  if current_user.email=="admin@gmail.com" %>
            <td><%= book.vendorname %></td>
            <td><%= book.vendormail %></td>
            <td><%= link_to 'Show', book %></td>
            <td><%= link_to 'Edit', edit_book_path(book) %></td>
            <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>

            <% else %>
            <td><%= link_to 'Show', book %></td>
            <% end %>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>
<% else %>
<section style="text-align:center; color: white;">
  <br><br><br><br><br>
  <h3>LIBRARY MANAGEMENT SYSTEM </h3><br>
  <pre>
  Login / Sign up to access
  </pre>
</section>
<% end %>




<script type="text/javascript">
  $(window).on("load resize ", function() {
  var scrollWidth = $('.tbl-content').width() - $('.tbl-content table').width();
  $('.tbl-header').css({'padding-right':scrollWidth});
}).resize();
</script>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/search.html.erb
<h3>Search results</h3>
<% results.each do |result| %>
	<%= result %>
<% end %>

app/views/books/show.html.erb
<style type="text/css">
  body{
  background: -webkit-linear-gradient(left, #25c481, #25b7c4);
  background: linear-gradient(to right, #25c481, #25b7c4);
  font-family: 'Roboto', sans-serif;
  color: white;
}
.card-bod{
  background-color: rgba(255,255,255,0.3);
  color: white;
  margin-right: 20%;
  margin-left: 20%;
  text-align: center;
}
</style>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<br><br><br>

<% if user_signed_in? %>

<body>
  <br><br>
  <p id="notice"><%= notice %></p>
  <div class="car">
    <div class="card-bod">
  <div  class="col-md-4 col-md-offset-4" style=" margin: 0 auto;margin-top:10%;">
  <h1 style="text-align:center;margin:bottom:10%;">Book</h1>
  <p>
    <strong>Bookname:</strong>
    <%= @book.bookname %>
  </p>

  <p>
    <strong>Bookdescription:</strong>
    <%= @book.bookdescription %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= @book.author %>
  </p>

  <p>
    <strong>Vendorname:</strong>
    <%= @book.vendorname %>
  </p>

  <p>
    <strong>Vendormail:</strong>
    <%= @book.vendormail %>
  </p>

  <p>
    <strong>Userid:</strong>
    <%= @book.userid %>
  </p>

<hr>
  <%  if current_user.email=="admin@gmail.com" %>

    <%= render @book.requests %>
  <% else %>

    <%= form_with(model: [@book, @book.requests.build]) do |f| %>
      <div class="form-group">
        <%= f.text_field :request,value:"Request", type: :hidden %>
        <%= f.number_field :user_id,value:current_user.id, type: :hidden %>

      </div>
      <%= f.submit 'Request', class: 'btn btn-primary' %>
    <% end %>

  <% end %>
<% if current_user.email=="admin@gmail.com" %>
  <%= link_to 'Edit', edit_book_path(@book) %> |<% end %>
  <%= link_to 'Back', books_path %> 
  </div>
  </div>
  </div>

</body>
<% end %>

app/views/layouts/_header.html.erb
<style type="text/css">
.form-control1{
  background: none;
  color: white;
  border: none;
  border-bottom: solid thin gray;
}
</style>

<div class="container">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top nav_my">
  <div class="container-fluid con_my" style="margin-left:60%;">
  	
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent" >
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 na">





        <% if user_signed_in? %>


        <li class="nav-item">
          <%= form_for "",url: books_path, role: "search", method: :get do %>
          <%= text_field_tag :search, @search_term, placeholder: "Search",class:"form-control1" %>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to 'Home', root_path, class:"nav-link active home" %>
        </li>

          <%  if current_user.email=="admin@gmail.com" %>
          <li class="nav-item" >
          <%= link_to 'Vendor List',vendors_path, class:"nav-link active vendorname" %>
          </li>
          <%=  %>
          <% end %>
          <li class="nav-item dropdown" >
            <a class="nav-link dropdown-toggle per" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="">
              <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16" style="float:left;margin:0;">
              <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
              </svg>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Edit profile',edit_user_registration_path, class:"dropdown-item registration" %>
              <li><hr class="dropdown-divider"></li>
              <%= link_to 'Log Out', destroy_user_session_path, class:"dropdown-item log_out" %>
            </ul>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to 'Log In', new_user_session_path, class:"nav-link active log_in" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Registration',new_user_registration_path, class:"nav-link active registration" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>
</div>

app/views/requests/_form.html.erb
<%= form_with(model: request) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :request %>
    <%= form.text_area :request %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.number_field :book_id %>
  </div>

  <div class="field">
    <%= form.label :parent_id %>
    <%= form.number_field :parent_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>Request</th>
      <th>Book</th>
      <th>Parent</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.request %></td>
        <td><%= request.book_id %></td>
        <td><%= request.parent_id %></td>
        <td><%= request.user_id %></td>
        <td><%= link_to 'Destroy', book_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Request:</strong>
  <%= @request.request %>
</p>

<p>
  <strong>Book:</strong>
  <%= @request.book_id %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @request.parent_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @request.user_id %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>

app/views/vendors/edit.html.erb
<style>
  .tbl-content{
  height:500px;
  overflow-x:auto;
  margin-top: 0px;
  border: 1px solid rgba(255,255,255,0.3);
  margin-right: 20%;
  margin-left: 20%;
  padding: 20px;
  color: white;
}
</style>
	<br><br>
<br><br>
<div class="tbl-content">


<h1>Editing Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>
</div>

app/views/vendors/index.html.erb
<style type="text/css">
 h1{
  font-size: 30px;
  color: #fff;
  text-transform: uppercase;
  font-weight: 300;
  text-align: center;
  margin-bottom: 15px;
}
table{
  width:100%;
  table-layout: fixed;
}
.tbl-header{
  background-color: rgba(255,255,255,0.3);
 }
.tbl-content{
  height:300px;
  overflow-x:auto;
  margin-top: 0px;
  border: 1px solid rgba(255,255,255,0.3);
}
th{
  padding: 20px 15px;
  text-align: left;
  font-weight: 500;
  font-size: 12px;
  color: #fff;
  text-transform: uppercase;
}
td{
  padding: 15px;
  text-align: left;
  vertical-align:middle;
  font-weight: 300;
  font-size: 12px;
  color: #fff;
  border-bottom: solid 1px rgba(255,255,255,0.1);
}

tr:hover{
  background-color: rgba(255,255,255,0.3);
}
/* demo styles */

@import url(https://fonts.googleapis.com/css?family=Roboto:400,500,300,700);
body{
  background: -webkit-linear-gradient(left, #25c481, #25b7c4);
  background: linear-gradient(to right, #25c481, #25b7c4);
  font-family: 'Roboto', sans-serif;
}
section{
  margin: 50px;
}


/* follow me template */
.made-with-love {
  margin-top: 40px;
  padding: 10px;
  clear: left;
  text-align: center;
  font-size: 10px;
  font-family: arial;
  color: #fff;
}
.made-with-love i {
  font-style: normal;
  color: #F50057;
  font-size: 14px;
  position: relative;
  top: 2px;
}
.made-with-love a {
  color: #fff;
  text-decoration: none;
}
.made-with-love a:hover {
  text-decoration: underline;
}


/* for custom scrollbar for webkit browser*/

::-webkit-scrollbar {
    width: 6px;
} 
::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
} 
::-webkit-scrollbar-thumb {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
}
</style>
<% if user_signed_in? %>
          <%  if current_user.email=="admin@gmail.com" %>

<br><br><br><br><br>
<p id="notice"><%= notice %></p>
<section>
  <h1>BOOKS TABLE</h1>
  <div class="tbl-header">
    <table cellpadding="0" cellspacing="0" border="0">
      <thead>
        <tr>
          <th>Vendor name</th>
          <th>Vendor mail</th>

          <th></th>
          <th></th>
          <th></th>
          <% else %>
          <th></th>
        <% end %>

        </tr>
      </thead>
    </table>
  </div>
  <div class="tbl-content">
    <table cellpadding="0" cellspacing="0" border="0">
      <tbody>
        <% @vendors.each do |vendor| %>
          <tr>
            <td><%= vendor.vendor_name %></td>
            <td><%= vendor.vendor_mail %></td>
            <td><%= link_to 'Show', vendor %></td>
            <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
            <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div><br>
<%= link_to 'New Vendor', new_vendor_path %>

</section>

<% else %>
<section style="text-align:center; color: white;">

</section>
<% end %>

app/views/vendors/new.html.erb
<style>
  .tbl-content{
  height:500px;
  overflow-x:auto;
  margin-top: 0px;
  border: 1px solid rgba(255,255,255,0.3);
  margin-right: 20%;
  margin-left: 20%;
  padding: 20px;
  color: white;
}
</style>
	<br><br>
<br><br>
<div class="tbl-content">

<h1>New Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Back', vendors_path %>
</div>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vendor name:</strong>
  <%= @vendor.vendor_name %>
</p>

<p>
  <strong>Vendor mail:</strong>
  <%= @vendor.vendor_mail %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>